# -*- coding: utf-8 -*-
"""audio/video to text using whisper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jc5bU6U6-ZQO_DKB_gjEH1n2GBMQvNQp
"""



!pip install git+https://github.com/openai/whisper.git
!sudo apt update && sudo apt install ffmpeg



!whisper "/content/drive/MyDrive/Colab Notebooks/How to Get the Transcript of a YouTube Video.mp4" --model medium.en

!whisper "/content/drive/MyDrive/Colab Notebooks/What_is_Machine_Learning_.mp3" --model medium.en